name: lastsaid
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.1
  json_path: 0.3.1
  page_transition: 2.0.4
  shared_preferences: 2.0.11
  timeago: 3.1.0
  url_launcher: 6.0.15
  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.1.0
  pinput: ^2.2.11
  flutter_switch: ^0.3.2
  custom_switch_button: ^0.5.0
  
  mask_text_input_formatter: ^2.4.0
  dotted_border: ^1.0.6
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  numberpicker: ^2.1.1
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
 
  fonts:
    - family: AirArabic
      fonts:
        - asset: assets/fonts/Air Strip Arabic.ttf
        
    - family: AirStrip
      fonts:
        - asset: assets/fonts/AirStripArabic.otf

    - family: ArialRounded
      fonts:
        - asset: assets/fonts/Arial Rounded MT.ttf

    - family: NotoRegular
      fonts:
        - asset: assets/fonts/notokufiarabic-regular.ttf

    - family: NotoBold
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 700
    - family: NotoRegular2
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Regular (2).ttf